title: PhD school on Evolution in Computational Pangenomics
preposition: at Como
description: >-
  School on Evolution in Computational Pangenomics
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://COPA24.pangenome.eu" 
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

remote_theme: "DigitaleGesellschaft/jekyll-theme-conference@v3.6.1"

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - vendor
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:
  lang: en
  show_errors: True

  # Navigation bar
  navigation:
    #    logo:
    #  name: Evolution in Computational Pangenomics
    #  # img: ''
    #  url: 'https://algolab.github.io/COPA24/'
    links:
      - name: Program
        relative_url: /program/
      - name: Lectures
        relative_url: /talks/
      - name: Speakers
        relative_url: /speakers/
      - name: Location
        relative_url: /location/

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    # logo:
    #   img: ''
    links:
      - name: Program
        relative_url: /program/
      - name: How to get there
        relative_url: /location/
      - name: Tickets
        disabled: true
        absolute_url: ''

   # Information boxes
  info_bars:
    - title: Welcome to the PhD school on Evolution in Computational Pangenomics 
      color: primary
      main_only: true
      text: The school is a [PANGAIA](https://pangenome.eu) event.
            Key dates
    - title: Registration deadline
      text: May 31st
      color: warning
      pages_only: true

  # Live indications
  #  live:
  #  date: 09.09.2024
  #  timezone: GMT+1
  #  stop:       240  # in minutes
  #  streaming:
  #    enable: true
  #    pause:     20  # in minutes
  #    prepend:    5  # in minutes
  #    extend:     5  # in minutes
  #  demo:
  #    enable: false
  #    duration: 300  # in seconds
  #    pause:     10  # in seconds

  talks:
    # Talk categories
    main_categories:
      - name: Lectures
        color: primary
      - name: Social
        color: secondary

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page.  Set `map: false` if you don't want to
    # display it.
    map:
      # Initial map center point
      home_coord: 45.82312,9.06741
      # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
      # The following do match the Bootstrap design not too badly:
      #   - Thunderforest.Neighbourhood
      #   - Esri.WorldTopoMap
      map_provider: "OpenStreetMap.Mapnik"
      default_zoom: 19


  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: false
